// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef MainWindow_h
#define MainWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Tree.H>
#include <FL/Fl_Menu_Bar.H>

class CubeViewUI {
public:
  CubeViewUI();
  Fl_Double_Window *mainWindow;
  static Fl_Menu_Item menu_[];
  void show(int argc, char **argv);
};
#endif
