
set PATH=C:/Program Files/Microsoft HPC Pack 2008 R2/Bin/;C:/Windows;C:/Windows/System32/Wbem;C:/Windows/System32/WindowsPowerShell/v1.0/;C:/Program Files/Intel/WiFi/bin/;C:/Program Files/Common Files/Intel/WirelessCommon/;C:/Program Files/Git/cmd;C:/Program Files/Git/mingw64/bin;C:/Program Files/Git/usr/bin;D:/Luciano/Programas/TortoiseSVN/bin;D:/Luciano/Programas/CMake/bin;C:/Program Files/Microsoft SQL Server/110/Tools/Binn/;C:/Program Files (x86)/Microsoft SDKs/TypeScript/1.0/;C:/Program Files/Microsoft SQLServer/120/Tools/Binn/;C:/Program Files/Common Files/Autodesk Shared/;C:/Program Files (x86)/Autodesk/Backburner/;D:/Luciano/Programas/TortoiseHG/;D:/Luciano/Programas/doxygen/bin;C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common;C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/;C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/110/Tools/Binn/;C:/Program Files (x86)/Microsoft SQL Server/120/Tools/Binn/;C:/Program Files/Microsoft SQL Server/120/DTS/Binn/;C:/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit/;C:/Program Files (x86)/Skype/Phone/;C:/SIMULIA/Abaqus/Commands;D:/Luciano/Programas/x86_64-5.3.0-posix-seh-rt_v4-rev0/mingw64/bin;D:/Luciano/Programas/CMake/bin;D:/Luciano/Programas/GetGnuWin32/bin;C:/Program Files/Intel/WiFi/bin/;C:/Program Files/Common Files/Intel/WirelessCommon/;D:/Luciano/Grafico/Libs/PixelLight/PixelLight-SDK/Runtime/x64;D:/Luciano/Programas/make/bin;D:/Luciano/Programas/x86_64-5.3.0-posix-seh-rt_v4-rev0/mingw64/bin;D:/Luciano/Libs/wxwidgets-3.1.0/include;D:\Luciano\Libs\VTK-6.3.0-Install\include\vtk-6.3;D:\Luciano\Libs\VTK-6.3.0-Install\lib

set CC="x86_64-w64-mingw32-gcc.exe"
set CXX="x86_64-w64-mingw32-g++.exe"

set VTK_DIR=D:/Luciano/Libs/vtk-6.3.0-release

set wxWidgets_ROOT_DIR=D:\Luciano\Libs\wxwidgets-3.1.0

cmake -G "CodeBlocks - MinGW Makefiles" -DCMAKE_C_COMPILER=%CC% -DCMAKE_CXX_COMPILER=%CC% -D CMAKE_INSTALL_PREFIX=D:/Luciano/Libs/VTK-6.3.0/CMake -DVTK_USE_HYBRID=ON -DVTK_USE_RENDERING=ON ../wxVTK-1.4/wxVTK